# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 02:32
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualTextLTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.IntegerField(default=0)),
                ('stm_id', models.IntegerField(default=0)),
                ('textstore_id', models.IntegerField(default=0)),
                ('text', models.CharField(default='', max_length=160, null=True)),
                ('text_type', models.CharField(default='user', max_length=120, null=True)),
                ('response_type', models.CharField(default='Open', max_length=100)),
                ('response', models.CharField(default='', max_length=160, null=True)),
                ('response_cat', models.CharField(default='', max_length=160, null=True)),
                ('response_cat_bin', models.IntegerField(blank=True, null=True)),
                ('response_dim', models.IntegerField(blank=True, null=True)),
                ('response_time', models.IntegerField(default=0)),
                ('time_response', models.DateTimeField(blank=True, null=True)),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('time_to_send_circa', models.CharField(default='AM', max_length=160, null=True)),
                ('time_to_send_day', models.CharField(default='', max_length=160, null=True)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
                ('simulated', models.IntegerField(default=0)),
                ('time_to_add', models.IntegerField(default=0)),
                ('series', models.IntegerField(default=0)),
                ('failed_series', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActualTextSTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_text', models.IntegerField(default=0)),
                ('text_id', models.IntegerField(default=0)),
                ('textstore_id', models.IntegerField(default=0)),
                ('text', models.CharField(default='', max_length=160, null=True)),
                ('response', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('response_type', models.CharField(default='Open', max_length=100)),
                ('text_type', models.CharField(default='user', max_length=120, null=True)),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
                ('simulated', models.IntegerField(default=0)),
                ('time_response', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.IntegerField(default=0)),
                ('series', models.IntegerField(default=0)),
                ('time_to_add', models.IntegerField(default=0)),
                ('failed_series', models.IntegerField(default=0)),
                ('ready_for_next', models.IntegerField(default=0)),
                ('consolidated', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, default='Verizon', max_length=100)),
                ('sms_address', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(default='user', max_length=30)),
                ('active', models.IntegerField(default=1)),
                ('prompts_per_week', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prompt_interval_minute_avg', models.IntegerField(default=10)),
                ('prompt_interval_minute_min', models.IntegerField(default=15)),
                ('prompt_interval_minute_max', models.IntegerField(default=1000)),
                ('time_to_declare_lost', models.IntegerField(default=61)),
                ('research_instr_dim_rate', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('research_prompt_multiple_rate', models.DecimalField(decimal_places=2, default=Decimal('0.2'), max_digits=3)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.CharField(default='', max_length=120, null=True)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('email_message', models.TextField(null=True)),
                ('email_content', models.TextField(null=True)),
                ('processed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontological_type', models.CharField(default='prompt', max_length=300, null=True)),
                ('ontological_name', models.CharField(default='system', max_length=300, null=True)),
                ('prompt_set', models.CharField(default='', max_length=300, null=True)),
                ('prompt_set_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prompt_set_percent_calc', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee', models.CharField(default='', max_length=120, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(null=True)),
                ('entry_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleTextLTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=160, null=True)),
                ('text_type', models.CharField(default='user', max_length=120, null=True)),
                ('system_text', models.IntegerField(default=0)),
                ('text_importance', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('response_type', models.CharField(default='Open', max_length=100)),
                ('show_user', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_altered', models.DateTimeField(blank=True, null=True)),
                ('stm_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleTextSTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=160, null=True)),
                ('system_text', models.IntegerField(default=0)),
                ('text_type', models.CharField(default='user', max_length=120, null=True)),
                ('text_importance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('response_type', models.CharField(default='Open', max_length=100)),
                ('show_user', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_altered', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prompttext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='How much XXX is in your present moment (0-10)?', max_length=500, null=True)),
                ('text_type', models.CharField(default='DIM', max_length=500, null=True)),
                ('text_percent', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Respite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateTimeField(blank=True, null=True)),
                ('respite_type', models.CharField(default='', max_length=120, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTypeStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(blank=True, default='0-10', max_length=100)),
                ('ordering_num', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserGenPromptFixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(default='', max_length=160, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('hr_range', models.IntegerField(default='1')),
                ('active', models.BooleanField(default=True)),
                ('response_type', models.CharField(blank=True, default='Open', max_length=100)),
                ('show_user', models.BooleanField(default=False)),
                ('repeat_denomination', models.CharField(blank=True, default='day', max_length=100)),
                ('repeat_number', models.IntegerField(default='1')),
                ('begin_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0))),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('send_text', models.BooleanField(default=False)),
                ('text_request_stop', models.BooleanField(default=False)),
                ('phone', models.CharField(default='', max_length=30, null=True)),
                ('carrier', models.CharField(blank=True, default='CHANGE ME', max_length=100)),
                ('sms_address', models.EmailField(default='', max_length=254, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=30)),
                ('sleep_time', models.TimeField(default=datetime.datetime(2016, 1, 30, 22, 0))),
                ('sleep_duration', models.IntegerField(default=8)),
                ('respite_until_datetime', models.DateTimeField(blank=True, null=True)),
                ('prompts_per_week', models.IntegerField(default=3)),
                ('exp_response_rate', models.DecimalField(decimal_places=2, default=Decimal('0.6'), max_digits=3)),
                ('exp_response_time_avg', models.IntegerField(default=5)),
                ('exp_response_time_min', models.IntegerField(default=1)),
                ('exp_response_time_max', models.IntegerField(default=60)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
