# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='', max_length=160)),
                ('emotion_type', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
