# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='emotion',
            field=models.CharField(default='p', max_length=160),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='emotion_type',
            field=models.CharField(default='p', max_length=120),
        ),
    ]
