# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='phone_input',
            field=models.CharField(default='(XXX) XXX - XXXX', max_length=30),
        ),
    ]
