# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 02:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0003_auto_20161002_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibletextstm',
            name='text_importance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='phone_input',
            field=models.CharField(default='', max_length=16),
        ),
    ]
