# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0003_auto_20160615_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
    ]
