# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0003_carrier_entry_incoming_outgoing_respite_usersetting_usersummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='intensive_period_on',
        ),
    ]
