# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0004_auto_20160615_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='prompt',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='entry',
            name='prompt_type',
            field=models.CharField(default='', max_length=160),
        ),
    ]
