# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 05:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0004_auto_20161003_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='wake_time',
            field=models.TimeField(default=datetime.datetime(2016, 1, 30, 22, 0)),
        ),
    ]
