# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0005_auto_20160622_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='prompts_per_day',
            field=models.IntegerField(default=3),
        ),
    ]
