# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0005_usersetting_wake_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='send_email_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='send_text_check',
            field=models.BooleanField(default=True),
        ),
    ]
