# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0006_auto_20160622_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDEV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(default='', max_length=160, null=True)),
                ('prompt_type', models.CharField(default='', max_length=160, null=True)),
                ('prompt_reply', models.IntegerField(blank=True, null=True)),
                ('time_to_add', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
                ('time_response', models.DateTimeField(blank=True, null=True)),
                ('response_time_seconds', models.IntegerField(default=0)),
                ('ready_for_next', models.BooleanField(default=True)),
                ('send_next_immediately', models.BooleanField(default=False)),
                ('series', models.IntegerField(default=0)),
                ('failed_series', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
