# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0007_auto_20161007_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='sleep_time_schedule',
            new_name='dead_begin',
        ),
        migrations.RenameField(
            model_name='usersetting',
            old_name='wake_time_schedule',
            new_name='dead_end',
        ),
    ]
