# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0008_auto_20160715_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydev',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettingdev',
            name='user',
        ),
        migrations.DeleteModel(
            name='EntryDEV',
        ),
        migrations.DeleteModel(
            name='UserSettingDEV',
        ),
    ]
