# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0009_auto_20161007_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='text_set',
            field=models.CharField(default='mindfulness', max_length=30),
        ),
    ]
