# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0010_experiencesetting_text_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesetting',
            name='text_set',
            field=models.CharField(default='specific_set_default', max_length=30),
        ),
    ]
