# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0010_auto_20160718_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prompt_id',
            field=models.IntegerField(default=0),
        ),
    ]
