# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0011_auto_20161007_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='delete_this',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiencesetting',
            name='number_of_texts_in_set',
            field=models.IntegerField(default=1),
        ),
    ]
