# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0012_auto_20161007_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextltm',
            name='experience_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actualtextstm',
            name='experience_id',
            field=models.IntegerField(default=0),
        ),
    ]
