# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0013_auto_20161007_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesetting',
            name='text_set',
            field=models.CharField(default='default_user_set', max_length=30),
        ),
    ]
