# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0014_auto_20161007_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletextltm',
            name='experience_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possibletextstm',
            name='experience_id',
            field=models.IntegerField(default=0),
        ),
    ]
