# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0014_entry_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time_to_send_circa',
            field=models.CharField(default='AM', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='time_to_send_day',
            field=models.CharField(default='', max_length=160, null=True),
        ),
    ]
