# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0015_auto_20160720_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='response_time',
            field=models.IntegerField(default=0),
        ),
    ]
