# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0016_auto_20161007_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
