# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0017_auto_20160802_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergenprompt',
            name='require_response',
            field=models.BooleanField(default=False),
        ),
    ]
