# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0018_usergenprompt_require_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='prompt_set',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
