# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0018_auto_20161007_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='ideal_id',
            field=models.IntegerField(default=0),
        ),
    ]
