# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0019_auto_20160802_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionontology',
            name='ontological_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
