# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0019_experiencesetting_ideal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='user_state',
            field=models.CharField(default='activate', max_length=100),
        ),
    ]
