# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0020_experiencesetting_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='active_experiences',
            field=models.CharField(default='user generator, research', max_length=5000),
        ),
        migrations.AlterField(
            model_name='possibletextstm',
            name='text_set',
            field=models.CharField(default='user generated', max_length=30, null=True),
        ),
    ]
