# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0021_auto_20160802_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotion',
            name='require_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion',
            name='show_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
