# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0022_auto_20161010_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualTextSTM_SIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_text', models.IntegerField(default=0)),
                ('text_id', models.IntegerField(default=0)),
                ('textstore_id', models.IntegerField(default=0)),
                ('experience_id', models.IntegerField(default=0)),
                ('text_set', models.CharField(default='', max_length=30, null=True)),
                ('text', models.CharField(default='', max_length=160, null=True)),
                ('response', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('response_type', models.CharField(default='Open', max_length=100)),
                ('text_type', models.CharField(default='user', max_length=120, null=True)),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
                ('simulated', models.IntegerField(default=0)),
                ('time_response', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.IntegerField(default=0)),
                ('series', models.IntegerField(default=0)),
                ('time_to_add', models.IntegerField(default=0)),
                ('failed_series', models.IntegerField(default=0)),
                ('ready_for_next', models.IntegerField(default=0)),
                ('consolidated', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
