# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0022_auto_20160802_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time_to_send_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='time_to_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
