# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0023_auto_20160804_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_to_send_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
