# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0023_actualtextstm_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='active_experiences',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
