# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 21:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0025_auto_20160808_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionontology',
            name='prompt_set_percent_calc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
