# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0028_usersetting_instr_dim_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prompt_full',
            field=models.CharField(default='', max_length=500),
        ),
    ]
