# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0028_auto_20161014_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletextstm',
            name='unique_text_set',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
