# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0029_entry_prompt_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prompt_reply_type',
            field=models.CharField(default='', max_length=160, null=True),
        ),
    ]
