# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0030_possibletextltm_csv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibletextltm',
            name='csv_id',
        ),
        migrations.AddField(
            model_name='possibletextstm',
            name='csv_id',
            field=models.IntegerField(default=0),
        ),
    ]
