# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0031_auto_20160813_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='emotion',
            new_name='prompt',
        ),
        migrations.AddField(
            model_name='emotion',
            name='prompt_type',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
