# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0031_auto_20161015_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='tags',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='experiencesetting',
            name='text_set',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='experiencesetting',
            name='time_to_declare_lost',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='experiencesetting',
            name='unique_text_set',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
