# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0032_auto_20160813_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='prompt',
            new_name='emotion',
        ),
    ]
