# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0032_auto_20161015_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetypestore',
            name='response_type',
            field=models.CharField(blank=True, default='0 to 10', max_length=100),
        ),
    ]
