# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0033_auto_20161020_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='description_long',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='responsetypestore',
            name='ordering_num',
            field=models.IntegerField(default=0),
        ),
    ]
