# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 21:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0033_auto_20160813_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenPromptStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usergenprompt_id', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_altered', models.DateTimeField(blank=True, null=True)),
                ('prompt_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prompt', models.CharField(default='', max_length=160, null=True)),
                ('active', models.BooleanField(default=True)),
                ('response_type', models.CharField(default='Open', max_length=100)),
                ('show_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usergenprompt',
            name='prompt_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
