# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0034_auto_20160813_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(default='0-10', max_length=1000)),
            ],
        ),
    ]
