# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0034_auto_20161022_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='ordering_num',
            field=models.IntegerField(default=0),
        ),
    ]
