# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0035_responsetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetype',
            name='response_type',
            field=models.CharField(default='0-10', max_length=100),
        ),
    ]
