# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 13:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0035_experiencesetting_ordering_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(default='', max_length=300, null=True)),
                ('unique_feed_name', models.CharField(default='', max_length=300, null=True)),
                ('feed_type', models.CharField(default='user', max_length=30)),
                ('ideal_id', models.IntegerField(default=0)),
                ('texts_per_week', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_to_declare_lost', models.IntegerField(default=15)),
                ('description', models.CharField(default='', max_length=1000, null=True)),
                ('description_long', models.CharField(default='', max_length=10000, null=True)),
                ('tags', models.CharField(default='', max_length=3000, null=True)),
                ('ordering_num', models.IntegerField(default=0)),
                ('user_state', models.CharField(default='activate', max_length=100)),
                ('number_of_texts_in_set', models.IntegerField(default=1)),
                ('delete_this', models.BooleanField(default=False)),
                ('active', models.IntegerField(default=1)),
                ('prompt_interval_minute_avg', models.IntegerField(default=10)),
                ('prompt_interval_minute_min', models.IntegerField(default=15)),
                ('prompt_interval_minute_max', models.IntegerField(default=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='experiencesetting',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExperienceSetting',
        ),
    ]
