# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0036_auto_20161029_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualtextltm',
            old_name='experience_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='actualtextstm',
            old_name='experience_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='actualtextstm_sim',
            old_name='experience_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='feedsetting',
            old_name='prompt_interval_minute_avg',
            new_name='text_interval_minute_avg',
        ),
        migrations.RenameField(
            model_name='feedsetting',
            old_name='prompt_interval_minute_max',
            new_name='text_interval_minute_max',
        ),
        migrations.RenameField(
            model_name='feedsetting',
            old_name='prompt_interval_minute_min',
            new_name='text_interval_minute_min',
        ),
        migrations.RenameField(
            model_name='possibletextltm',
            old_name='experience_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='possibletextstm',
            old_name='experience_id',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='possibletextstm',
            old_name='text_set',
            new_name='feed_name',
        ),
        migrations.RenameField(
            model_name='possibletextstm',
            old_name='unique_text_set',
            new_name='unique_feed_name',
        ),
    ]
