# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0037_auto_20160814_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseType',
            new_name='ResponseTypeStore',
        ),
    ]
