# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0038_auto_20160814_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetypestore',
            name='text_percent',
            field=models.IntegerField(default=10),
        ),
    ]
