# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0039_responsetypestore_text_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsetypestore',
            old_name='text_percent',
            new_name='ordering_num',
        ),
    ]
