# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0039_auto_20161029_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='prompts_per_week',
            new_name='texts_per_week',
        ),
    ]
