# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0040_auto_20160814_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenprompt',
            name='prompt_percent',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
