# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0041_auto_20161029_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualtextltm',
            old_name='text_set',
            new_name='feed_name',
        ),
        migrations.RenameField(
            model_name='actualtextltm',
            old_name='text_type',
            new_name='feed_type',
        ),
    ]
