# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0042_auto_20161029_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsetting',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='feeds',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='group_name',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='group_type',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='joinable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='unique_group_name',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='viewable',
            field=models.BooleanField(default=False),
        ),
    ]
