# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0042_usergenpromptfixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergenpromptfixed',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usergenpromptfixed',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergenpromptfixed',
            name='hr_begin',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='usergenpromptfixed',
            name='hr_end',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AddField(
            model_name='usergenpromptfixed',
            name='response_type',
            field=models.CharField(blank=True, default='Open', max_length=100),
        ),
        migrations.AddField(
            model_name='usergenpromptfixed',
            name='show_user',
            field=models.BooleanField(default=False),
        ),
    ]
