# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0043_auto_20161029_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsetting',
            name='group_type',
            field=models.CharField(default='library', max_length=30),
        ),
    ]
