# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0045_auto_20160819_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenpromptfixed',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
