# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0045_groupsetting_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsetting',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedsetting',
            name='joinable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedsetting',
            name='viewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsetting',
            name='passcode',
            field=models.CharField(default='library', max_length=30),
        ),
    ]
