# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0046_auto_20161029_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletextltm',
            name='feed_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
