# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0046_auto_20160819_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergenpromptfixed',
            old_name='date_begin',
            new_name='begin_datetime',
        ),
        migrations.RenameField(
            model_name='usergenpromptfixed',
            old_name='date_end',
            new_name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='usergenpromptfixed',
            name='hr_begin',
        ),
        migrations.RemoveField(
            model_name='usergenpromptfixed',
            name='hr_end',
        ),
    ]
