# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0047_auto_20160823_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergenpromptfixed',
            name='hr_range',
            field=models.IntegerField(default='1'),
        ),
    ]
