# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0049_groupsetting_ideal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtextltm',
            name='feed_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='actualtextstm',
            name='feed_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='actualtextstm_sim',
            name='feed_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='possibletextltm',
            name='feed_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='possibletextstm',
            name='feed_name',
            field=models.CharField(default='user generated', max_length=300, null=True),
        ),
    ]
