# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0050_auto_20160830_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time_to_send_localtz',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
