# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0050_auto_20161204_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='sleep_time_in',
            field=models.CharField(default='11 PM', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='wake_time_in',
            field=models.CharField(default='7 AM', max_length=30, null=True),
        ),
    ]
