# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 14:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0051_entry_time_to_send_localtz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontological_type', models.CharField(default='prompt', max_length=300, null=True)),
                ('ontological_name', models.CharField(default='', max_length=300, null=True)),
                ('prompt_set', models.CharField(default='', max_length=300, null=True)),
                ('prompt_set_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prompt_set_percent_calc', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='emotionontology',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmotionOntology',
        ),
    ]
