# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0051_auto_20161213_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextstm_sim',
            name='notuser',
            field=models.IntegerField(default=0),
        ),
    ]
