# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0052_auto_20160831_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='ontological_name',
            field=models.CharField(default='system', max_length=300, null=True),
        ),
    ]
