# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0052_actualtextstm_sim_notuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='send_text_tmp',
            field=models.BooleanField(default=False),
        ),
    ]
