# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0053_usersetting_send_text_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualtextltm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='actualtextstm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='actualtextstm_sim',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedsetting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupsetting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ontology',
            name='user',
        ),
        migrations.RemoveField(
            model_name='possibletextltm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='possibletextstm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='respite',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResponseTypeStore',
        ),
        migrations.RemoveField(
            model_name='usergenpromptfixed',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActualTextLTM',
        ),
        migrations.DeleteModel(
            name='ActualTextSTM',
        ),
        migrations.DeleteModel(
            name='ActualTextSTM_SIM',
        ),
        migrations.DeleteModel(
            name='FeedSetting',
        ),
        migrations.DeleteModel(
            name='GroupSetting',
        ),
        migrations.DeleteModel(
            name='Ontology',
        ),
        migrations.DeleteModel(
            name='PossibleTextLTM',
        ),
        migrations.DeleteModel(
            name='PossibleTextSTM',
        ),
        migrations.DeleteModel(
            name='Respite',
        ),
        migrations.DeleteModel(
            name='UserGenPromptFixed',
        ),
    ]
