# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0053_auto_20160831_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergenprompt',
            name='noise_from_initialization',
            field=models.IntegerField(default=0),
        ),
    ]
