# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0054_auto_20170114_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcutalText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=160)),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(blank=True, default='', max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(default='', max_length=160)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=160)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('feed', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ent.Feed')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acutaltext',
            name='feed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ent.Feed'),
        ),
        migrations.AddField(
            model_name='acutaltext',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
