# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0054_usergenprompt_noise_from_initialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='top_prompt_1',
            field=models.CharField(default='good', max_length=300),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='top_prompt_2',
            field=models.CharField(default='bad', max_length=300),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='top_prompt_3',
            field=models.CharField(default='neutral', max_length=300),
        ),
    ]
