# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0055_auto_20170114_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('feed', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ent.Feed')),
                ('text', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ent.PossibleText')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='acutaltext',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='acutaltext',
            name='user',
        ),
        migrations.DeleteModel(
            name='AcutalText',
        ),
    ]
