# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0056_auto_20160916_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prompt_reply_bin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt_reply_dim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt_reply_open',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
