# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0058_auto_20170114_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtext',
            name='text',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='ent.PossibleText'),
        ),
    ]
