# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0058_auto_20160921_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextstm',
            name='response',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='actualtextstm',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
