# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0059_auto_20160921_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextltm',
            name='response_type',
            field=models.CharField(default='Open', max_length=100),
        ),
        migrations.AddField(
            model_name='actualtextstm',
            name='response_type',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
