# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 20:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0059_auto_20170114_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(default='', max_length=160)),
                ('description', models.CharField(default='', max_length=160)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('hour_start', models.TimeField(default=datetime.datetime(2016, 1, 30, 22, 0))),
                ('hour_end', models.TimeField(default=datetime.datetime(2016, 1, 30, 22, 0))),
                ('fuzzy', models.BooleanField(default=False)),
                ('iti', models.IntegerField(blank=True, null=True)),
                ('iti_noise', models.IntegerField(blank=True, null=True)),
                ('repeat_in_window', models.IntegerField(blank=True, null=True)),
                ('repeat_weeks', models.IntegerField(blank=True, null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='actualtext',
            name='text',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ent.PossibleText'),
        ),
        migrations.AlterField(
            model_name='possibletext',
            name='feed',
            field=models.ManyToManyField(default=1, related_name='texts', to='ent.Feed'),
        ),
    ]
