# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0060_auto_20160921_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextstm',
            name='time_response',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
