# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0061_actualtextstm_time_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextstm',
            name='time_to_add',
            field=models.IntegerField(default=0),
        ),
    ]
