# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0061_possibletext_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibletext',
            name='timing',
        ),
    ]
