# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0063_possibletext_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='show_user',
            field=models.BooleanField(default=True),
        ),
    ]
