# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0064_actualtextstm_failed_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextstm',
            name='ready_for_next',
            field=models.BooleanField(default=True),
        ),
    ]
