# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0065_actualtextstm_ready_for_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextltm',
            name='time_to_send_circa',
            field=models.CharField(default='AM', max_length=160, null=True),
        ),
    ]
