# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0066_auto_20170117_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='tag',
            field=models.ManyToManyField(blank=True, to='ent.Tag'),
        ),
        migrations.AlterField(
            model_name='possibletext',
            name='tag',
            field=models.ManyToManyField(blank=True, to='ent.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=160, null=True, unique=True),
        ),
    ]
