# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0067_actualtextltm_time_to_send_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletextltm',
            name='stm_id',
            field=models.IntegerField(default=0),
        ),
    ]
