# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0067_auto_20170117_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletext',
            name='repeat_summary',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
