# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0069_auto_20160922_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibletextltm',
            name='time_to_add',
        ),
        migrations.RemoveField(
            model_name='possibletextstm',
            name='time_to_add',
        ),
        migrations.AddField(
            model_name='actualtextltm',
            name='time_to_add',
            field=models.IntegerField(default=0),
        ),
    ]
