# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0070_auto_20170118_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='date_end_value',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='timing',
            name='date_start_value',
            field=models.CharField(default='', max_length=160),
        ),
    ]
