# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0070_auto_20160922_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextltm',
            name='failed_series',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actualtextltm',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
