# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 01:22
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0071_auto_20160923_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextExperienceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(default='user', max_length=30)),
                ('prompt_interval_minute_avg', models.IntegerField(default=10)),
                ('prompt_interval_minute_min', models.IntegerField(default=15)),
                ('prompt_interval_minute_max', models.IntegerField(default=1000)),
                ('time_to_declare_lost', models.IntegerField(default=61)),
                ('research_instr_dim_rate', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('research_prompt_multiple_rate', models.DecimalField(decimal_places=2, default=Decimal('0.2'), max_digits=3)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='emotion_core_rate',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='emotion_ontology_current',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='emotion_other_rate',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='emotion_top100_rate',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='global_settings_current',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='instr_dim_rate',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='instruction_rate',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='prompt_interval_minute_avg',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='prompt_interval_minute_max',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='prompt_interval_minute_min',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='prompt_multiple_rate',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='teaching_period_on',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='time_to_declare_lost',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='top_prompt_1',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='top_prompt_2',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='top_prompt_3',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='user_settings_current',
        ),
        migrations.AlterField(
            model_name='possibletextltm',
            name='text_importance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
