# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0071_auto_20170118_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
