# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0072_auto_20160923_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextExperienceSettings',
            new_name='ExperienceSettings',
        ),
    ]
