# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0073_auto_20160923_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceSettings',
            new_name='ExperienceSetting',
        ),
    ]
