# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0073_auto_20170119_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualtext',
            name='feed',
        ),
    ]
