# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0074_auto_20160923_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtextstm',
            name='ready_for_next',
            field=models.IntegerField(default=0),
        ),
    ]
