# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0074_remove_actualtext_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualtext',
            old_name='time_reponse',
            new_name='time_response',
        ),
    ]
