# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0076_auto_20170120_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='explict_save',
            field=models.BooleanField(default=False),
        ),
    ]
