# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0076_auto_20160923_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='prompts_per_week',
            field=models.IntegerField(default=3),
        ),
    ]
