# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0077_experiencesetting_prompts_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesetting',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
