# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0077_collection_explict_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
