# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0078_experiencesetting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtextstm',
            name='response',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
    ]
