# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0078_collection_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='active_experiences',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='exp_response_rate',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='exp_response_time_avg',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='exp_response_time_max',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='exp_response_time_min',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='new_user_pages',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='respite_until_datetime',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='sleep_duration',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='sleep_time',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='sleep_time_in',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='texts_per_week',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='wake_time',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='wake_time_in',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='research_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
