# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0079_auto_20160930_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextstm',
            name='consolidated',
            field=models.IntegerField(default=0),
        ),
    ]
