# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0080_possibletext_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='fuzzy_denomination',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='timing',
            name='iti_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
