# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0080_actualtextstm_consolidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextltm',
            name='stm_id',
            field=models.IntegerField(default=0),
        ),
    ]
