# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0081_actualtextltm_stm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtextltm',
            name='response_cat_bin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
