# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0081_auto_20170123_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='addressee',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='message',
        ),
        migrations.AddField(
            model_name='outgoing',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.ActualText'),
        ),
    ]
