# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0082_auto_20170131_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletext',
            name='date_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
