# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0085_usersetting_timezone_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibletext',
            name='timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.Timing'),
        ),
    ]
