# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 00:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0085_possibletextstm_system_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesetting',
            name='prompts_per_week',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
