# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0086_auto_20170203_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletext',
            name='intended_collection',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='possibletext',
            name='intended_tags',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
