# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0086_auto_20161002_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='user_generated_prompt_rate',
        ),
    ]
