# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0087_auto_20170203_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='intended_text',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
