# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0088_timing_intended_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='picture_name',
            new_name='collection_name',
        ),
        migrations.AddField(
            model_name='collection',
            name='intended_tags',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
