# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-14 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0090_auto_20170514_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
