# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0091_timing_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletext',
            name='tmp_save',
            field=models.BooleanField(default=True),
        ),
    ]
