# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-17 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0092_possibletext_tmp_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='settings_complete',
            field=models.BooleanField(default=False),
        ),
    ]
