# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0094_auto_20170523_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=5000, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='possibletext',
            name='collection',
            field=models.ManyToManyField(blank=True, default=1, related_name='texts', to='ent.Collection'),
        ),
    ]
