# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0095_auto_20170531_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
