# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0099_quicksuggestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletext',
            name='input_text',
            field=models.CharField(default='', max_length=160),
        ),
    ]
