# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0100_possibletext_input_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='intended_text_input',
            field=models.CharField(default='', max_length=160),
        ),
    ]
