# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-03 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0101_timing_intended_text_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='new_user_step',
            field=models.IntegerField(default=0),
        ),
    ]
