# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0105_quotation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(default='', max_length=160)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='possibletext',
            name='alternate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.AlternateText'),
        ),
    ]
