# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0108_auto_20170609_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtext',
            name='text_sent',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
