# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0109_actualtext_text_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtext',
            name='alt_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.AlternateText'),
        ),
    ]
