# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0110_actualtext_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtext',
            name='alt_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.AlternateText'),
        ),
    ]
