# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0111_auto_20170609_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatetext',
            name='input_text',
            field=models.CharField(default='', max_length=160),
        ),
    ]
