# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0112_alternatetext_input_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatetext',
            name='intended_text',
            field=models.CharField(default='', max_length=160),
        ),
    ]
