# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0113_alternatetext_intended_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatetext',
            name='input_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='alternatetext',
            name='intended_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
