# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0115_auto_20170612_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=1000)),
                ('link_display', models.CharField(default='', max_length=1000)),
                ('intended_text_type', models.CharField(default='', max_length=500)),
                ('intended_text', models.CharField(default='', max_length=500)),
                ('input_text', models.CharField(default='', max_length=1500)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='textdescription',
            name='description_type',
        ),
        migrations.AlterField(
            model_name='alternatetext',
            name='description',
            field=models.ManyToManyField(blank=True, to='ent.TextLink'),
        ),
        migrations.AlterField(
            model_name='possibletext',
            name='description',
            field=models.ManyToManyField(blank=True, to='ent.TextLink'),
        ),
    ]
