# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0116_auto_20170612_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatetext',
            name='link',
            field=models.ManyToManyField(blank=True, to='ent.TextLink'),
        ),
        migrations.AddField(
            model_name='possibletext',
            name='link',
            field=models.ManyToManyField(blank=True, to='ent.TextLink'),
        ),
        migrations.AlterField(
            model_name='alternatetext',
            name='description',
            field=models.ManyToManyField(blank=True, to='ent.TextDescription'),
        ),
        migrations.AlterField(
            model_name='possibletext',
            name='description',
            field=models.ManyToManyField(blank=True, to='ent.TextDescription'),
        ),
    ]
