# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0117_auto_20170612_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='text_request_stop_tmp',
            field=models.BooleanField(default=False),
        ),
    ]
