# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0119_auto_20170615_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletext',
            name='text_type',
            field=models.CharField(default='standard', max_length=160),
        ),
    ]
