# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0120_possibletext_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibletext',
            name='timing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.Timing'),
        ),
    ]
