# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0121_auto_20170616_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibletext',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='texts', to='ent.Collection'),
        ),
    ]
