# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0122_auto_20170616_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='text_type',
            field=models.CharField(default='standard', max_length=160),
        ),
    ]
