# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0124_collection_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='location',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
