# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-05 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0125_usersetting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletext',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
