# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0128_auto_20170705_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtext',
            name='original_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_text', to='ent.PossibleText'),
        ),
    ]
