# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ent', '0130_remove_actualtext_original_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=160)),
                ('text_type', models.CharField(default='standard', max_length=160)),
                ('input_text', models.CharField(default='', max_length=160)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('tmp_save', models.BooleanField(default=True)),
                ('quick_suggestion', models.BooleanField(default=False)),
                ('intended_collection', models.CharField(blank=True, max_length=160, null=True)),
                ('intended_tags', models.CharField(blank=True, max_length=600, null=True)),
                ('alt_text', models.ManyToManyField(blank=True, related_name='ideal_alts', to='ent.AlternateText')),
                ('collection', models.ManyToManyField(blank=True, related_name='ideal_program', to='ent.Collection')),
                ('description', models.ManyToManyField(blank=True, to='ent.TextDescription')),
                ('link', models.ManyToManyField(blank=True, to='ent.TextLink')),
                ('tag', models.ManyToManyField(blank=True, to='ent.Tag')),
                ('timing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideal_timing', to='ent.Timing')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='possibletext',
            name='ideal_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideal_text', to='ent.IdealText'),
        ),
    ]
