# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0133_auto_20170706_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibletext',
            name='ideal_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possible_text', to='ent.IdealText'),
        ),
    ]
