# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0134_auto_20170711_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='collection', to='ent.Tag'),
        ),
    ]
