# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0135_auto_20170727_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksuggestion',
            name='text',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ent.IdealText'),
        ),
    ]
