# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0136_auto_20170727_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibletext',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='possible_texts', to='ent.Collection'),
        ),
    ]
