# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-28 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0137_auto_20170727_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(default='', max_length=160)),
                ('program_name', models.CharField(default='', max_length=160)),
                ('ordering', models.CharField(default='', max_length=160)),
                ('author', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=3000)),
                ('long_description', models.TextField(default='', max_length=3000)),
                ('publish', models.BooleanField(default=False)),
                ('explict_save', models.BooleanField(default=False)),
                ('intended_tags', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.RenameField(
            model_name='idealtext',
            old_name='intended_collection',
            new_name='intended_program',
        ),
        migrations.RenameField(
            model_name='possibletext',
            old_name='intended_collection',
            new_name='intended_program',
        ),
        migrations.RemoveField(
            model_name='idealtext',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='possibletext',
            name='collection',
        ),
    ]
