# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-28 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professional', '0018_auto_20170728_1242'),
        ('ent', '0138_auto_20170728_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='program',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='program', to='ent.Tag'),
        ),
        migrations.AddField(
            model_name='program',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idealtext',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='ideal_texts', to='ent.Program'),
        ),
        migrations.AddField(
            model_name='possibletext',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='possible_texts', to='ent.Program'),
        ),
    ]
