# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0139_auto_20170728_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksuggestion',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.IdealText'),
        ),
    ]
