# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
