# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_auto_20170704_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ent.UserSetting'),
        ),
    ]
