# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0005_auto_20170704_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
