# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0128_auto_20170705_2008'),
        ('professional', '0007_auto_20170705_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='programs',
            field=models.ManyToManyField(blank=True, to='ent.Collection'),
        ),
    ]
