# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-05 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0008_person_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='programs',
            new_name='collection',
        ),
    ]
