# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0133_auto_20170706_1704'),
        ('professional', '0009_auto_20170705_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='collection',
            field=models.ManyToManyField(blank=True, to='ent.Collection'),
        ),
    ]
