# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0011_group_ideal_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='group', to='ent.Collection'),
        ),
    ]
