# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0012_auto_20170707_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='person', to='ent.Collection'),
        ),
    ]
