# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0133_auto_20170706_1704'),
        ('professional', '0013_auto_20170707_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='possible_text',
            field=models.ManyToManyField(blank=True, related_name='group', to='ent.PossibleText'),
        ),
    ]
