# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0015_auto_20170711_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='group', to='professional.Person'),
        ),
    ]
