# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0134_auto_20170711_0205'),
        ('professional', '0016_auto_20170711_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ideal_text',
            field=models.ManyToManyField(blank=True, related_name='person', to='ent.IdealText'),
        ),
    ]
