# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:07
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDEV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_user', models.CharField(default='', max_length=160, null=True)),
                ('prompt', models.CharField(default='', max_length=160, null=True)),
                ('prompt_type', models.CharField(default='', max_length=160, null=True)),
                ('prompt_reply', models.IntegerField(blank=True, null=True)),
                ('time_to_add', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
                ('time_response', models.DateTimeField(blank=True, null=True)),
                ('response_time_seconds', models.IntegerField(default=0)),
                ('ready_for_next', models.BooleanField(default=True)),
                ('send_next_immediately', models.BooleanField(default=False)),
                ('series', models.IntegerField(default=0)),
                ('failed_series', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettingDEV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(default='default', max_length=300, null=True)),
                ('num_to_gen', models.IntegerField(default=100)),
                ('send_text', models.BooleanField(default=False)),
                ('teaching_period_on', models.BooleanField(default=True)),
                ('text_request_stop', models.BooleanField(default=False)),
                ('phone', models.CharField(default='', max_length=30, null=True)),
                ('carrier', models.CharField(blank=True, default='CHANGE ME', max_length=100)),
                ('sms_address', models.EmailField(default='', max_length=254, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=30)),
                ('sleep_time', models.TimeField(default=datetime.datetime(2016, 1, 30, 22, 0))),
                ('sleep_duration', models.DecimalField(decimal_places=2, default=Decimal('8.0'), max_digits=3)),
                ('respite_until_datetime', models.DateTimeField(blank=True, null=True)),
                ('prompts_per_day', models.IntegerField(default=3)),
                ('prompt_interval_minute_avg', models.IntegerField(default=10)),
                ('prompt_interval_minute_min', models.IntegerField(default=15)),
                ('prompt_interval_minute_max', models.IntegerField(default=1000)),
                ('emotion_core_rate', models.DecimalField(decimal_places=2, default=Decimal('0.6'), max_digits=3)),
                ('emotion_top100_rate', models.DecimalField(decimal_places=2, default=Decimal('0.3'), max_digits=3)),
                ('emotion_other_rate', models.DecimalField(decimal_places=2, default=Decimal('0.1'), max_digits=3)),
                ('user_generated_prompt_rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prompt_multiple_rate', models.DecimalField(decimal_places=2, default=Decimal('0.2'), max_digits=3)),
                ('instruction_rate', models.DecimalField(decimal_places=2, default=Decimal('0.2'), max_digits=3)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
