# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettingdev',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='usersettingdev',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='usersettingdev',
            name='send_text',
        ),
        migrations.RemoveField(
            model_name='usersettingdev',
            name='sms_address',
        ),
        migrations.RemoveField(
            model_name='usersettingdev',
            name='teaching_period_on',
        ),
        migrations.RemoveField(
            model_name='usersettingdev',
            name='text_request_stop',
        ),
        migrations.RemoveField(
            model_name='usersettingdev',
            name='timezone',
        ),
    ]
