# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettingdev',
            old_name='prompt_interval_minute_avg',
            new_name='text_interval_minute_avg',
        ),
        migrations.RenameField(
            model_name='usersettingdev',
            old_name='prompt_interval_minute_max',
            new_name='text_interval_minute_max',
        ),
        migrations.RenameField(
            model_name='usersettingdev',
            old_name='prompt_interval_minute_min',
            new_name='text_interval_minute_min',
        ),
    ]
