# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 06:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0002_auto_20160716_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettingdev',
            name='begin_date',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
