# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:50
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0003_usersettingdev_begin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettingdev',
            name='exp_response_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.6'), max_digits=3),
        ),
        migrations.AddField(
            model_name='usersettingdev',
            name='exp_response_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='usersettingdev',
            name='time_to_declare_lost',
            field=models.IntegerField(default=30),
        ),
    ]
