# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0004_auto_20160716_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettingdev',
            name='exp_response_time',
        ),
        migrations.AddField(
            model_name='usersettingdev',
            name='exp_response_time_avg',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usersettingdev',
            name='exp_response_time_max',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='usersettingdev',
            name='exp_response_time_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersettingdev',
            name='time_to_declare_lost',
            field=models.IntegerField(default=61),
        ),
    ]
