# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0005_auto_20160716_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrydev',
            old_name='response_time_seconds',
            new_name='response_time',
        ),
    ]
