# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 18:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0008_remove_entrydevsum_prompt_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydevsum',
            name='prompt_reply_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3, null=True),
        ),
    ]
