# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0009_auto_20160717_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydevsum',
            name='prompt_reply_avg',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
