# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0010_auto_20160717_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydev',
            name='time_to_send_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
