# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0011_entrydev_time_to_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydev',
            name='time_to_send_day',
            field=models.CharField(default='', max_length=160, null=True),
        ),
    ]
