# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0012_entrydev_time_to_send_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydevsum',
            name='analysis',
            field=models.CharField(default='', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='entrydevsum',
            name='day',
            field=models.CharField(default='', max_length=160, null=True),
        ),
    ]
