# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0013_auto_20160718_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrydevsum',
            old_name='day',
            new_name='time_to_send_day',
        ),
    ]
