# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0015_auto_20160718_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydev',
            name='prompt_id',
            field=models.IntegerField(default=0),
        ),
    ]
