# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vis', '0016_entrydev_prompt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionToShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='', max_length=160, null=True)),
                ('emotion_id', models.IntegerField(default=0)),
                ('show_me', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
