# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0017_emotiontoshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotiontoshow',
            old_name='show_me',
            new_name='show_me_graph',
        ),
        migrations.AddField(
            model_name='emotiontoshow',
            name='show_me_user',
            field=models.BooleanField(default=True),
        ),
    ]
