# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0018_auto_20160720_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettingdev',
            old_name='prompts_per_day',
            new_name='prompts_per_week',
        ),
    ]
