# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimini_help',
            old_name='help_heading',
            new_name='help_name',
        ),
        migrations.RemoveField(
            model_name='sentimini_help',
            name='level',
        ),
        migrations.RemoveField(
            model_name='sentimini_help',
            name='minor_cat',
        ),
        migrations.AddField(
            model_name='sentimini_help',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
