# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0002_auto_20161015_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimini_help',
            name='starting_item',
            field=models.IntegerField(default=0),
        ),
    ]
