# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0003_faquserquestions_typer'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion_instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=1000, null=True)),
                ('emotion', models.CharField(default='', max_length=1000, null=True)),
                ('quotation', models.CharField(default='', max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='emotion_quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=1000, null=True)),
                ('emotion', models.CharField(default='', max_length=1000, null=True)),
                ('quotation', models.CharField(default='', max_length=3000, null=True)),
            ],
        ),
    ]
