# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0004_emotion_instruction_emotion_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_quotation',
            name='author',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
    ]
