# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0005_emotion_quotation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_instruction',
            name='why',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='emotion_quotation',
            name='quotation',
            field=models.TextField(default='', null=True),
        ),
    ]
