# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0006_auto_20160716_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_instruction',
            name='quotation',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
    ]
