# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0008_emotion_quotation_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_quotation_display',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotion_quotation_display',
            name='show_me',
            field=models.IntegerField(default=0),
        ),
    ]
