# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0010_emotion_instruction_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_instruction',
            name='quotation',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='emotion_instruction_display',
            name='instruction',
            field=models.CharField(default='QUOTATION: EMOTIONS MAKE UP OUR WORLD', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='emotion_quotation',
            name='quotation',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='emotion_quotation_display',
            name='quotation',
            field=models.CharField(default='QUOTATION: EMOTIONS MAKE UP OUR WORLD', max_length=3000, null=True),
        ),
    ]
