# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scaffold', '0011_auto_20160721_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='BETAsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.IntegerField(default=0)),
                ('how_many_prompts', models.IntegerField(default=0)),
                ('text_topics', models.CharField(default='', max_length=1000, null=True)),
                ('desired_dollars', models.IntegerField(default=0)),
                ('max_dollars', models.IntegerField(default=0)),
                ('new_features', models.CharField(default='', max_length=1000, null=True)),
                ('new_directions', models.CharField(default='', max_length=1000, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
