# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0013_auto_20160803_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion_statement_display',
            old_name='quotation',
            new_name='statement',
        ),
    ]
