# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0014_auto_20160803_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_likes',
            name='like_switch',
            field=models.IntegerField(default=0),
        ),
    ]
