# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0015_user_likes_like_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_instruction',
            name='quotation',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='emotion_quotation',
            name='quotation',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='emotion_statement_display',
            name='statement',
            field=models.TextField(default='QUOTATION: EMOTIONS MAKE UP OUR WORLD', max_length=3000, null=True),
        ),
    ]
