# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0017_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_altered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
