# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0019_auto_20160916_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default='Default Content Here', max_length=100000),
        ),
    ]
