# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scaffold', '0021_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Business Set 1', max_length=300)),
                ('con_price_per_outgoing', models.DecimalField(decimal_places=5, default=0.0035, max_digits=5)),
                ('con_price_per_inccming', models.DecimalField(decimal_places=5, default=0.0, max_digits=5)),
                ('con_number_outgoing_per_user_per_day', models.IntegerField(default=5)),
                ('con_number_ingoing_per_user_per_day', models.IntegerField(default=3)),
                ('con_conversation_rate_to_paid', models.DecimalField(decimal_places=5, max_digits=5)),
                ('con_return_per_paying_user_per_month', models.IntegerField(default=10)),
                ('static_human_cost_per_month', models.IntegerField(default=5800)),
                ('static_server_cost_per_month', models.IntegerField(default=150)),
                ('static_other_cost_per_month', models.IntegerField(default=150)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
