# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0022_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='con_conversation_rate_to_paid',
            field=models.DecimalField(decimal_places=3, default=0.01, max_digits=3),
        ),
    ]
