# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0023_auto_20160918_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='con_number_ingoing_per_user_per_day',
        ),
        migrations.RemoveField(
            model_name='business',
            name='con_number_outgoing_per_user_per_day',
        ),
        migrations.AddField(
            model_name='business',
            name='con_number_ingoing_per_free_per_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='business',
            name='con_number_ingoing_per_paid_per_day',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='business',
            name='con_number_outgoing_per_free_per_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='business',
            name='con_number_outgoing_per_paid_per_day',
            field=models.IntegerField(default=10),
        ),
    ]
