# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scaffold', '0024_auto_20160918_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Set Name', max_length=300)),
                ('measure', models.CharField(default='Measure Name', max_length=300)),
                ('super_measure', models.CharField(default='Super Measure', max_length=300)),
                ('measure_type', models.CharField(default='Dimensional', max_length=300)),
                ('population', models.CharField(default='Group', max_length=300)),
                ('minval', models.IntegerField(default=0)),
                ('maxval', models.IntegerField(default=10)),
                ('mean', models.IntegerField(default=5)),
                ('sd', models.IntegerField(default=3)),
                ('distr', models.CharField(default='Normal', max_length=300)),
                ('response_rate', models.IntegerField(default=60)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
