# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scaffold', '0026_auto_20160928_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentimini_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_heading', models.CharField(default='Text', max_length=300)),
                ('help_content', models.CharField(default='Default content', max_length=300)),
                ('help_type', models.CharField(default='Glossary', max_length=300)),
                ('major_cat', models.CharField(default='Settings', max_length=300)),
                ('minor_cat', models.CharField(default='Texts', max_length=300)),
                ('level', models.CharField(default='', max_length=300)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
