# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0027_sentimini_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimini_help',
            name='help_content',
            field=models.TextField(default='Default content', max_length=10000),
        ),
    ]
