# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold', '0028_auto_20161001_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimini_help',
            name='level',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
